// Generated by lsc from edit-diff.ts

datatype TextReplacement = TextReplacement(matchIndex: int, matchLength: int, newText: string)

method applyReplacements(content: string, replacements: seq<TextReplacement>, offset: int) returns (res: string)
  requires forall k: nat :: ((k < |replacements|) ==> (replacements[k].matchLength >= 0))
  requires forall k: nat :: ((k < |replacements|) ==> ((0 <= (replacements[k].matchIndex - offset)) && (((replacements[k].matchIndex - offset) + replacements[k].matchLength) <= |content|)))
  requires forall k: nat :: (((k + 1) < |replacements|) ==> ((replacements[k].matchIndex + replacements[k].matchLength) <= replacements[(k + 1)].matchIndex))
{
  var result := content;
  var i := (|replacements| - 1);
  while (i >= 0)
    invariant (-1 <= i)
    invariant (i < |replacements|)
    invariant ((if ((i + 1) < |replacements|) then (replacements[(i + 1)].matchIndex - offset) else |content|) <= |result|)
    invariant (result[0..(if ((i + 1) < |replacements|) then (replacements[(i + 1)].matchIndex - offset) else |content|)] == content[0..(if ((i + 1) < |replacements|) then (replacements[(i + 1)].matchIndex - offset) else |content|)])
    decreases (i + 1)
  {
    var replacement := replacements[i];
    var matchIndex := (replacement.matchIndex - offset);
    result := ((result[0..matchIndex] + replacement.newText) + result[(matchIndex + replacement.matchLength)..]);
    i := (i - 1);
  }
  return result;
}
