/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

structure TruncationResult where
  content : String
  truncated : Bool
  truncatedBy : Option String
  totalLines : Int
  totalBytes : Int
  outputLines : Int
  outputBytes : Int
  lastLinePartial : Bool
  firstLineExceedsLimit : Bool
  maxLines : Int
  maxBytes : Int
deriving Repr, Inhabited, DecidableEq

structure TruncationOptions where
  maxLines : Option Int
  maxBytes : Option Int
deriving Repr, Inhabited, DecidableEq

opaque Buffer_byteLength (s : String) (enc : String) : Int
@[grind] axiom Buffer_byteLength_spec (s : String) (enc : String) : (Buffer_byteLength s enc ≥ 0)

opaque splitLinesForCounting (content : String) : Array String
@[grind] axiom splitLinesForCounting_spec (content : String) : (content.length > 0 → (splitLinesForCounting content).size > 0)

opaque truncateStringToBytesFromEnd (str : String) (maxBytes : Int) : String
