// Generated by lsc from truncate.ts

datatype Option<T> = None | Some(value: T)

function SeqJoin(s: seq<string>, sep: string): string
  decreases |s|
{
  if |s| == 0 then ""
  else if |s| == 1 then s[0]
  else s[0] + sep + SeqJoin(s[1..], sep)
}

function {:axiom} Buffer_byteLength(s: string, enc: string): int
  ensures (Buffer_byteLength(s, enc) >= 0)

function {:axiom} splitLinesForCounting(content: string): seq<string>
  ensures ((|content| > 0) ==> (|splitLinesForCounting(content)| > 0))

function {:axiom} truncateStringToBytesFromEnd(str: string, maxBytes: int): string

datatype TruncationResult = TruncationResult(content: string, truncated: bool, truncatedBy: Option<string>, totalLines: int, totalBytes: int, outputLines: int, outputBytes: int, lastLinePartial: bool, firstLineExceedsLimit: bool, maxLines: int, maxBytes: int)

datatype TruncationOptions = TruncationOptions(maxLines: Option<int>, maxBytes: Option<int>)

const DEFAULT_MAX_LINES: int := 2000

const DEFAULT_MAX_BYTES: int := (50 * 1024)

method truncateHead(content: string, options: TruncationOptions) returns (res: TruncationResult)
  requires (|content| > 0)
  ensures ((res.maxLines >= 0) ==> (res.outputLines <= res.maxLines))
  ensures (res.outputLines <= res.totalLines)
  ensures ((match res.truncatedBy { case Some(i_value) => (i_value == "bytes") case None => false }) ==> !(res.firstLineExceedsLimit) ==> (res.outputLines < res.maxLines))
{
  var maxLines := (match options.maxLines { case Some(i_oc0_val) => i_oc0_val case None => DEFAULT_MAX_LINES });
  var maxBytes := (match options.maxBytes { case Some(i_oc1_val) => i_oc1_val case None => DEFAULT_MAX_BYTES });
  var totalBytes := Buffer_byteLength(content, "utf-8");
  var lines := splitLinesForCounting(content);
  var totalLines := |lines|;
  if ((totalLines <= maxLines) && (totalBytes <= maxBytes)) {
    return TruncationResult(content, false, None, totalLines, totalBytes, totalLines, totalBytes, false, false, maxLines, maxBytes);
  }
  var firstLineBytes := Buffer_byteLength(lines[0], "utf-8");
  if (firstLineBytes > maxBytes) {
    return TruncationResult("", true, Some("bytes"), totalLines, totalBytes, 0, 0, false, true, maxLines, maxBytes);
  }
  var outputLinesArr: seq<string> := [];
  var outputBytesCount := 0;
  var truncatedBy := "lines";
  var i := 0;
  while ((i < |lines|) && (i < maxLines))
    invariant (0 <= i)
    invariant (i <= |lines|)
    invariant ((i == 0) || (i <= maxLines))
    invariant (|outputLinesArr| == i)
    invariant (outputBytesCount <= maxBytes)
    decreases (|lines| - i)
  {
    var line := lines[i];
    var lineBytes := (Buffer_byteLength(line, "utf-8") + (if (i > 0) then 1 else 0));
    if ((outputBytesCount + lineBytes) > maxBytes) {
      truncatedBy := "bytes";
      break;
    }
    outputLinesArr := (outputLinesArr + [line]);
    outputBytesCount := (outputBytesCount + lineBytes);
    i := (i + 1);
  }
  if ((|outputLinesArr| >= maxLines) && (outputBytesCount <= maxBytes)) {
    truncatedBy := "lines";
  }
  var outputContent := SeqJoin(outputLinesArr, "\n");
  var finalOutputBytes := Buffer_byteLength(outputContent, "utf-8");
  return TruncationResult(outputContent, true, Some(truncatedBy), totalLines, totalBytes, |outputLinesArr|, finalOutputBytes, false, false, maxLines, maxBytes);
}

method truncateTail(content: string, options: TruncationOptions) returns (res: TruncationResult)
  requires (|content| > 0)
  ensures ((res.maxLines >= 0) ==> (res.outputLines <= res.maxLines))
  ensures (res.outputLines <= res.totalLines)
  ensures ((res.maxBytes >= 0) ==> (match res.truncatedBy { case Some(i_value) => (i_value == "bytes") case None => false }) ==> !(res.lastLinePartial) ==> (res.outputLines < res.maxLines))
{
  var maxLines := (match options.maxLines { case Some(i_oc2_val) => i_oc2_val case None => DEFAULT_MAX_LINES });
  var maxBytes := (match options.maxBytes { case Some(i_oc3_val) => i_oc3_val case None => DEFAULT_MAX_BYTES });
  var totalBytes := Buffer_byteLength(content, "utf-8");
  var lines := splitLinesForCounting(content);
  var totalLines := |lines|;
  if ((totalLines <= maxLines) && (totalBytes <= maxBytes)) {
    return TruncationResult(content, false, None, totalLines, totalBytes, totalLines, totalBytes, false, false, maxLines, maxBytes);
  }
  var outputLinesArr: seq<string> := [];
  var outputBytesCount := 0;
  var truncatedBy := "lines";
  var lastLinePartial := false;
  var i := (|lines| - 1);
  while (((i >= 0) && (|outputLinesArr| < maxLines)) && (truncatedBy != "bytes"))
    invariant (i >= -1)
    invariant (lastLinePartial ==> (truncatedBy == "bytes"))
    invariant ((truncatedBy != "bytes") ==> !(lastLinePartial) ==> (|outputLinesArr| == ((|lines| - 1) - i)))
    invariant ((truncatedBy == "bytes") ==> (|outputLinesArr| <= |lines|))
    invariant ((|outputLinesArr| == 0) || (|outputLinesArr| <= maxLines))
    invariant (((outputBytesCount <= maxBytes) || (outputBytesCount == 0)) || lastLinePartial)
    invariant ((truncatedBy == "bytes") ==> !(lastLinePartial) ==> (|outputLinesArr| < maxLines))
    decreases (i + 1)
  {
    var line := lines[i];
    var lineBytes := (Buffer_byteLength(line, "utf-8") + (if (|outputLinesArr| > 0) then 1 else 0));
    if ((outputBytesCount + lineBytes) > maxBytes) {
      truncatedBy := "bytes";
      if (|outputLinesArr| == 0) {
        var truncatedLine := truncateStringToBytesFromEnd(line, maxBytes);
        outputLinesArr := ([truncatedLine] + outputLinesArr);
        outputBytesCount := Buffer_byteLength(truncatedLine, "utf-8");
        lastLinePartial := true;
      }
    } else {
      outputLinesArr := ([line] + outputLinesArr);
      outputBytesCount := (outputBytesCount + lineBytes);
    }
    i := (i - 1);
  }
  if ((|outputLinesArr| >= maxLines) && (outputBytesCount <= maxBytes)) {
    truncatedBy := "lines";
  }
  var outputContent := SeqJoin(outputLinesArr, "\n");
  var finalOutputBytes := Buffer_byteLength(outputContent, "utf-8");
  return TruncationResult(outputContent, true, Some(truncatedBy), totalLines, totalBytes, |outputLinesArr|, finalOutputBytes, lastLinePartial, false, maxLines, maxBytes);
}
