/-
  Generated by lsc from truncate.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «truncate.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

def DEFAULT_MAX_LINES : Int := 2000

def DEFAULT_MAX_BYTES : Int := 50 * 1024

method truncateHead (content : String) (options : TruncationOptions) return (res : TruncationResult)
  require content.length > 0
  ensures res.maxLines ≥ 0 → res.outputLines ≤ res.maxLines
  ensures res.outputLines ≤ res.totalLines
  ensures (match res.truncatedBy with | .some _value => _value == "bytes" | .none => false) → ¬(res.firstLineExceedsLimit) → res.outputLines < res.maxLines
  do
    let maxLines : Int := (match options.maxLines with | .some _oc0_val => _oc0_val | .none => DEFAULT_MAX_LINES)
    let maxBytes : Int := (match options.maxBytes with | .some _oc1_val => _oc1_val | .none => DEFAULT_MAX_BYTES)
    let totalBytes := Buffer_byteLength content "utf-8"
    let mut lines : Array String := splitLinesForCounting content
    let totalLines := lines.size
    if totalLines ≤ maxLines && totalBytes ≤ maxBytes then
      return { content := content, truncated := false, truncatedBy := none, totalLines := totalLines, totalBytes := totalBytes, outputLines := totalLines, outputBytes := totalBytes, lastLinePartial := false, firstLineExceedsLimit := false, maxLines := maxLines, maxBytes := maxBytes }
    let firstLineBytes := Buffer_byteLength lines[0]! "utf-8"
    if firstLineBytes > maxBytes then
      return { content := "", truncated := true, truncatedBy := some "bytes", totalLines := totalLines, totalBytes := totalBytes, outputLines := 0, outputBytes := 0, lastLinePartial := false, firstLineExceedsLimit := true, maxLines := maxLines, maxBytes := maxBytes }
    let mut outputLinesArr : Array String := #[]
    let mut outputBytesCount : Int := 0
    let mut truncatedBy : String := "lines"
    let mut i : Int := 0
    while i < lines.size && i < maxLines
      invariant 0 ≤ i
      invariant i ≤ lines.size
      invariant i = 0 ∨ i ≤ maxLines
      invariant outputLinesArr.size = i
      invariant outputBytesCount ≤ maxBytes
      done_with True
      decreasing (lines.size - i).toNat
    do
      let line := lines[i.toNat]!
      let lineBytes := Buffer_byteLength line "utf-8" + (if i > 0 then 1 else 0)
      if outputBytesCount + lineBytes > maxBytes then
        truncatedBy := "bytes"
        break
      outputLinesArr := Array.push outputLinesArr line
      outputBytesCount := outputBytesCount + lineBytes
      i := i + 1
    if outputLinesArr.size ≥ maxLines && outputBytesCount ≤ maxBytes then
      truncatedBy := "lines"
    let outputContent := (String.intercalate "\n" outputLinesArr.toList)
    let finalOutputBytes := Buffer_byteLength outputContent "utf-8"
    return { content := outputContent, truncated := true, truncatedBy := some truncatedBy, totalLines := totalLines, totalBytes := totalBytes, outputLines := outputLinesArr.size, outputBytes := finalOutputBytes, lastLinePartial := false, firstLineExceedsLimit := false, maxLines := maxLines, maxBytes := maxBytes }

method truncateTail (content : String) (options : TruncationOptions) return (res : TruncationResult)
  require content.length > 0
  ensures res.maxLines ≥ 0 → res.outputLines ≤ res.maxLines
  ensures res.outputLines ≤ res.totalLines
  ensures res.maxBytes ≥ 0 → (match res.truncatedBy with | .some _value => _value == "bytes" | .none => false) → ¬(res.lastLinePartial) → res.outputLines < res.maxLines
  do
    let maxLines : Int := (match options.maxLines with | .some _oc2_val => _oc2_val | .none => DEFAULT_MAX_LINES)
    let maxBytes : Int := (match options.maxBytes with | .some _oc3_val => _oc3_val | .none => DEFAULT_MAX_BYTES)
    let totalBytes := Buffer_byteLength content "utf-8"
    let mut lines : Array String := splitLinesForCounting content
    let totalLines := lines.size
    if totalLines ≤ maxLines && totalBytes ≤ maxBytes then
      return { content := content, truncated := false, truncatedBy := none, totalLines := totalLines, totalBytes := totalBytes, outputLines := totalLines, outputBytes := totalBytes, lastLinePartial := false, firstLineExceedsLimit := false, maxLines := maxLines, maxBytes := maxBytes }
    let mut outputLinesArr : Array String := #[]
    let mut outputBytesCount : Int := 0
    let mut truncatedBy : String := "lines"
    let mut lastLinePartial : Bool := false
    let mut i : Int := lines.size - 1
    while i ≥ 0 && outputLinesArr.size < maxLines && truncatedBy ≠ "bytes"
      invariant i ≥ -1
      invariant lastLinePartial → truncatedBy = "bytes"
      invariant truncatedBy ≠ "bytes" → ¬(lastLinePartial) → outputLinesArr.size = lines.size - 1 - i
      invariant truncatedBy = "bytes" → outputLinesArr.size ≤ lines.size
      invariant outputLinesArr.size = 0 ∨ outputLinesArr.size ≤ maxLines
      invariant outputBytesCount ≤ maxBytes ∨ outputBytesCount = 0 ∨ lastLinePartial
      invariant truncatedBy = "bytes" → ¬(lastLinePartial) → outputLinesArr.size < maxLines
      decreasing (i + 1).toNat
    do
      let line := lines[i.toNat]!
      let lineBytes := Buffer_byteLength line "utf-8" + (if outputLinesArr.size > 0 then 1 else 0)
      if outputBytesCount + lineBytes > maxBytes then
        truncatedBy := "bytes"
        if outputLinesArr.size = 0 then
          let truncatedLine := truncateStringToBytesFromEnd line maxBytes
          outputLinesArr := (#[truncatedLine] ++ outputLinesArr)
          outputBytesCount := Buffer_byteLength truncatedLine "utf-8"
          lastLinePartial := true
      else
        outputLinesArr := (#[line] ++ outputLinesArr)
        outputBytesCount := outputBytesCount + lineBytes
      i := i - 1
    if outputLinesArr.size ≥ maxLines && outputBytesCount ≤ maxBytes then
      truncatedBy := "lines"
    let outputContent := (String.intercalate "\n" outputLinesArr.toList)
    let finalOutputBytes := Buffer_byteLength outputContent "utf-8"
    return { content := outputContent, truncated := true, truncatedBy := some truncatedBy, totalLines := totalLines, totalBytes := totalBytes, outputLines := outputLinesArr.size, outputBytes := finalOutputBytes, lastLinePartial := lastLinePartial, firstLineExceedsLimit := false, maxLines := maxLines, maxBytes := maxBytes }
