/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

structure ChangelogEntry where
  major : Int
  minor : Int
  patch : Int
  content : String
deriving Repr, Inhabited, DecidableEq

namespace Pure

def compareVersions (v1 : ChangelogEntry) (v2 : ChangelogEntry) : Int :=
  if v1.major ≠ v2.major then
    v1.major - v2.major
  else
    if v1.minor ≠ v2.minor then
      v1.minor - v2.minor
    else
      v1.patch - v2.patch

end Pure
