/-
  Generated by lsc from changelog.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «changelog.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method compareVersions (v1 : ChangelogEntry) (v2 : ChangelogEntry) return (res : Int)
  ensures res > 0 ↔ v1.major > v2.major ∨ v1.major = v2.major ∧ v1.minor > v2.minor ∨ v1.major = v2.major ∧ v1.minor = v2.minor ∧ v1.patch > v2.patch
  ensures res < 0 ↔ v1.major < v2.major ∨ v1.major = v2.major ∧ v1.minor < v2.minor ∨ v1.major = v2.major ∧ v1.minor = v2.minor ∧ v1.patch < v2.patch
  ensures res = 0 ↔ v1.major = v2.major ∧ v1.minor = v2.minor ∧ v1.patch = v2.patch
  do
    return Pure.compareVersions v1 v2
