// Generated by lsc from changelog.ts

datatype ChangelogEntry = ChangelogEntry(major: int, minor: int, patch: int, content: string)

function compareVersions(v1: ChangelogEntry, v2: ChangelogEntry): int
{
  if (v1.major != v2.major) then
    (v1.major - v2.major)
  else
    if (v1.minor != v2.minor) then
      (v1.minor - v2.minor)
    else
      (v1.patch - v2.patch)
}

lemma compareVersions_ensures(v1: ChangelogEntry, v2: ChangelogEntry)
  ensures ((compareVersions(v1, v2) > 0) <==> (((v1.major > v2.major) || ((v1.major == v2.major) && (v1.minor > v2.minor))) || (((v1.major == v2.major) && (v1.minor == v2.minor)) && (v1.patch > v2.patch))))
  ensures ((compareVersions(v1, v2) < 0) <==> (((v1.major < v2.major) || ((v1.major == v2.major) && (v1.minor < v2.minor))) || (((v1.major == v2.major) && (v1.minor == v2.minor)) && (v1.patch < v2.patch))))
  ensures ((compareVersions(v1, v2) == 0) <==> (((v1.major == v2.major) && (v1.minor == v2.minor)) && (v1.patch == v2.patch)))
{
}
