// Generated by lsc from models.ts

function SeqIndexOf<T(==)>(s: seq<T>, x: T): int
  ensures -1 <= SeqIndexOf(s, x) < |s|
  ensures SeqIndexOf(s, x) >= 0 ==> s[SeqIndexOf(s, x)] == x
  ensures SeqIndexOf(s, x) == -1 ==> x !in s
{
  SeqIndexOfFrom(s, x, 0)
}

function SeqIndexOfFrom<T(==)>(s: seq<T>, x: T, from: nat): int
  requires from <= |s|
  ensures -1 <= SeqIndexOfFrom(s, x, from) < |s|
  ensures SeqIndexOfFrom(s, x, from) >= 0 ==> s[SeqIndexOfFrom(s, x, from)] == x
  ensures SeqIndexOfFrom(s, x, from) == -1 ==> forall i :: from <= i < |s| ==> s[i] != x
  decreases |s| - from
{
  if from == |s| then -1
  else if s[from] == x then from as int
  else SeqIndexOfFrom(s, x, from + 1)
}

function {:axiom} getSupportedThinkingLevels<TApi>(model: Model<TApi>): seq<ModelThinkingLevel>

datatype ModelThinkingLevel = off | minimal | low | medium | high | xhigh

datatype Model<TApi> = Model(reasoning: bool)

const EXTENDED_THINKING_LEVELS: seq<ModelThinkingLevel> := [ModelThinkingLevel.off, ModelThinkingLevel.minimal, ModelThinkingLevel.low, ModelThinkingLevel.medium, ModelThinkingLevel.high, ModelThinkingLevel.xhigh]

method clampThinkingLevel<TApi>(model: Model<TApi>, level: ModelThinkingLevel) returns (res: ModelThinkingLevel)
  ensures ((res in getSupportedThinkingLevels(model)) || res.off?)
  ensures ((level in getSupportedThinkingLevels(model)) ==> (res == level))
  ensures ((res in getSupportedThinkingLevels(model)) ==> (SeqIndexOf(EXTENDED_THINKING_LEVELS, level) <= SeqIndexOf(EXTENDED_THINKING_LEVELS, res)) ==> forall k: int :: ((SeqIndexOf(EXTENDED_THINKING_LEVELS, level) <= k) ==> (k < SeqIndexOf(EXTENDED_THINKING_LEVELS, res)) ==> !((EXTENDED_THINKING_LEVELS[k] in getSupportedThinkingLevels(model)))))
  ensures ((res in getSupportedThinkingLevels(model)) ==> (SeqIndexOf(EXTENDED_THINKING_LEVELS, res) < SeqIndexOf(EXTENDED_THINKING_LEVELS, level)) ==> forall k: int :: ((SeqIndexOf(EXTENDED_THINKING_LEVELS, level) <= k) ==> (k < |EXTENDED_THINKING_LEVELS|) ==> !((EXTENDED_THINKING_LEVELS[k] in getSupportedThinkingLevels(model)))))
  ensures ((res in getSupportedThinkingLevels(model)) ==> (SeqIndexOf(EXTENDED_THINKING_LEVELS, res) < SeqIndexOf(EXTENDED_THINKING_LEVELS, level)) ==> forall k: int :: ((SeqIndexOf(EXTENDED_THINKING_LEVELS, res) < k) ==> (k < SeqIndexOf(EXTENDED_THINKING_LEVELS, level)) ==> !((EXTENDED_THINKING_LEVELS[k] in getSupportedThinkingLevels(model)))))
{
  var availableLevels := getSupportedThinkingLevels(model);
  if (level in availableLevels) {
    return level;
  }
  var requestedIndex := SeqIndexOf(EXTENDED_THINKING_LEVELS, level);
  if (requestedIndex == -1) {
    return (if ((0 <= 0) && (0 < |availableLevels|)) then availableLevels[0] else ModelThinkingLevel.off);
  }
  var i := requestedIndex;
  while (i < |EXTENDED_THINKING_LEVELS|)
    invariant (requestedIndex <= i)
    invariant (i <= |EXTENDED_THINKING_LEVELS|)
    invariant forall k: int :: ((requestedIndex <= k) ==> (k < i) ==> !((EXTENDED_THINKING_LEVELS[k] in availableLevels)))
  {
    var candidate := EXTENDED_THINKING_LEVELS[i];
    if (candidate in availableLevels) {
      return candidate;
    }
    i := (i + 1);
  }
  var i_2 := (requestedIndex - 1);
  while (i_2 >= 0)
    invariant (-1 <= i_2)
    invariant (i_2 < requestedIndex)
    invariant forall k: int :: ((i_2 < k) ==> (k < requestedIndex) ==> !((EXTENDED_THINKING_LEVELS[k] in availableLevels)))
    invariant forall k: int :: ((requestedIndex <= k) ==> (k < |EXTENDED_THINKING_LEVELS|) ==> !((EXTENDED_THINKING_LEVELS[k] in availableLevels)))
  {
    var candidate := EXTENDED_THINKING_LEVELS[i_2];
    if (candidate in availableLevels) {
      return candidate;
    }
    i_2 := (i_2 - 1);
  }
  return (if ((0 <= 0) && (0 < |availableLevels|)) then availableLevels[0] else ModelThinkingLevel.off);
}
