// Generated by lsc from compaction.ts

datatype Option<T> = None | Some(value: T)

datatype Role = bashExecution | custom | branchSummary | compactionSummary | user | assistant | toolResult

datatype AgentMessage = AgentMessage(role: Role)

type Opaque_TextContent_or_ImageContent(==)

datatype ArrayOf_Opaque_TextContent_or_ImageContent_Or_string = ArrayBranch(arr: seq<Opaque_TextContent_or_ImageContent>) | NonArrayBranch(val: string)

datatype SessionTreeEntry = message(message: AgentMessage, id: string, parentId: Option<string>, timestamp: string) | thinking_level_change(thinkingLevel: string, id: string, parentId: Option<string>, timestamp: string) | model_change(provider: string, modelId: string, id: string, parentId: Option<string>, timestamp: string) | compaction(summary: string, firstKeptEntryId: string, tokensBefore: int, details: Option<int>, fromHook: Option<bool>, id: string, parentId: Option<string>, timestamp: string) | branch_summary(fromId: string, summary: string, details: Option<int>, fromHook: Option<bool>, id: string, parentId: Option<string>, timestamp: string) | custom(customType: string, data: Option<int>, id: string, parentId: Option<string>, timestamp: string) | custom_message(customType: string, content: ArrayOf_Opaque_TextContent_or_ImageContent_Or_string, details: Option<int>, display: bool, id: string, parentId: Option<string>, timestamp: string) | label_(targetId_label: string, label_: Option<string>, id: string, parentId: Option<string>, timestamp: string) | session_info(name: Option<string>, id: string, parentId: Option<string>, timestamp: string) | leaf(targetId_leaf: Option<string>, id: string, parentId: Option<string>, timestamp: string)

datatype MessageEntry = MessageEntry(type_: string, message: AgentMessage, id: string, parentId: Option<string>, timestamp: string)

datatype ThinkingLevelChangeEntry = ThinkingLevelChangeEntry(type_: string, thinkingLevel: string, id: string, parentId: Option<string>, timestamp: string)

datatype ModelChangeEntry = ModelChangeEntry(type_: string, provider: string, modelId: string, id: string, parentId: Option<string>, timestamp: string)

datatype CompactionEntry = CompactionEntry(type_: string, summary: string, firstKeptEntryId: string, tokensBefore: int, details: Option<int>, fromHook: Option<bool>, id: string, parentId: Option<string>, timestamp: string)

datatype BranchSummaryEntry = BranchSummaryEntry(type_: string, fromId: string, summary: string, details: Option<int>, fromHook: Option<bool>, id: string, parentId: Option<string>, timestamp: string)

datatype CustomEntry = CustomEntry(type_: string, customType: string, data: Option<int>, id: string, parentId: Option<string>, timestamp: string)

datatype CustomMessageEntry = CustomMessageEntry(type_: string, customType: string, content: ArrayOf_Opaque_TextContent_or_ImageContent_Or_string, details: Option<int>, display: bool, id: string, parentId: Option<string>, timestamp: string)

datatype TextContent = TextContent(type_: string, text: string, textSignature: Option<string>)

datatype ImageContent = ImageContent(type_: string, data: string, mimeType: string)

datatype LabelEntry = LabelEntry(type_: string, targetId: string, label_: Option<string>, id: string, parentId: Option<string>, timestamp: string)

datatype SessionInfoEntry = SessionInfoEntry(type_: string, name: Option<string>, id: string, parentId: Option<string>, timestamp: string)

datatype LeafEntry = LeafEntry(type_: string, targetId: Option<string>, id: string, parentId: Option<string>, timestamp: string)

method findValidCutPoints(entries: seq<SessionTreeEntry>, startIndex: int, endIndex: int) returns (res: seq<int>)
  requires (0 <= startIndex)
  requires (endIndex <= |entries|)
  ensures forall k: nat :: ((k < |res|) ==> ((startIndex <= res[k]) && (res[k] < endIndex)))
  ensures forall k: nat :: ((k < |res|) ==> !((entries[res[k]].message? && entries[res[k]].message.role.toolResult?)))
{
  var cutPoints: seq<int> := [];
  var i := startIndex;
  while (i < endIndex)
    invariant (startIndex <= i)
    invariant forall k: nat :: ((k < |cutPoints|) ==> ((startIndex <= cutPoints[k]) && (cutPoints[k] < endIndex)))
    invariant forall k: nat :: ((k < |cutPoints|) ==> !((entries[cutPoints[k]].message? && entries[cutPoints[k]].message.role.toolResult?)))
  {
    var entry := entries[i];
    match entry {
      case message(i_entry_message, i_entry_id, i_entry_parentId, i_entry_timestamp) =>
        var role := i_entry_message.role;
        match role {
          case bashExecution =>
            cutPoints := (cutPoints + [i]);
          case custom =>
            cutPoints := (cutPoints + [i]);
          case branchSummary =>
            cutPoints := (cutPoints + [i]);
          case compactionSummary =>
            cutPoints := (cutPoints + [i]);
          case user =>
            cutPoints := (cutPoints + [i]);
          case assistant =>
            cutPoints := (cutPoints + [i]);
          case toolResult =>

        }
      case thinking_level_change(i_entry_thinkingLevel, i_entry_id, i_entry_parentId, i_entry_timestamp) =>

      case model_change(i_entry_provider, i_entry_modelId, i_entry_id, i_entry_parentId, i_entry_timestamp) =>

      case compaction(i_entry_summary, i_entry_firstKeptEntryId, i_entry_tokensBefore, i_entry_details, i_entry_fromHook, i_entry_id, i_entry_parentId, i_entry_timestamp) =>

      case branch_summary(i_entry_fromId, i_entry_summary, i_entry_details, i_entry_fromHook, i_entry_id, i_entry_parentId, i_entry_timestamp) =>

      case custom(i_entry_customType, i_entry_data, i_entry_id, i_entry_parentId, i_entry_timestamp) =>

      case custom_message(i_entry_customType, i_entry_content, i_entry_details, i_entry_display, i_entry_id, i_entry_parentId, i_entry_timestamp) =>

      case label_(i_entry_targetId, i_entry_label, i_entry_id, i_entry_parentId, i_entry_timestamp) =>

      case session_info(i_entry_name, i_entry_id, i_entry_parentId, i_entry_timestamp) =>

      case leaf(i_entry_targetId, i_entry_id, i_entry_parentId, i_entry_timestamp) =>

    }
    if (entry.branch_summary? || entry.custom_message?) {
      cutPoints := (cutPoints + [i]);
    }
    i := (i + 1);
  }
  return cutPoints;
}
