/-
  Generated by lsc from compaction.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «compaction-cli.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method isToolResultMessage (entry : SessionEntry) return (res : Bool)
  do
    return Pure.isToolResultMessage entry

method isTurnStarter (entry : SessionEntry) return (res : Bool)
  do
    return Pure.isTurnStarter entry

method isCutPointMessage (message : AgentMessage) return (res : Bool)
  do
    return Pure.isCutPointMessage message

method isTurnStartMessage (message : AgentMessage) return (res : Bool)
  do
    return Pure.isTurnStartMessage message

method isTurnStartEntry (entry : SessionEntry) return (res : Bool)
  ensures res = false ∨ Pure.isTurnStarter entry
  do
    return Pure.isTurnStartEntry entry

method findValidCutPoints (entries : Array SessionEntry) (startIndex : Int) (endIndex : Int) return (res : Array Int)
  require 0 ≤ startIndex
  require endIndex ≤ entries.size
  ensures ∀ k : Nat, k < res.size → startIndex ≤ res[k]! ∧ res[k]! < endIndex
  ensures ∀ k : Nat, k < res.size → ¬(Pure.isToolResultMessage entries[(res[k]!).toNat]!)
  do
    let mut cutPoints : Array Int := #[]
    let mut i : Int := startIndex
    while i < endIndex
      invariant startIndex ≤ i
      invariant ∀ k : Nat, k < cutPoints.size → startIndex ≤ cutPoints[k]! ∧ cutPoints[k]! < endIndex
      invariant ∀ k : Nat, k < cutPoints.size → ¬(Pure.isToolResultMessage entries[(cutPoints[k]!).toNat]!)
      decreasing (endIndex - i).toNat
    do
      let entry := entries[i.toNat]!
      if (match entry with | .compaction .. => true | _ => false) then
        i := i + 1
      else
        if (sessionEntryToContextMessages entry).any Pure.isCutPointMessage then
          cutPoints := Array.push cutPoints i
        i := i + 1
    return cutPoints

method findTurnStartIndex (entries : Array SessionEntry) (entryIndex : Int) (startIndex : Int) return (res : Int)
  require 0 ≤ startIndex
  require entryIndex < entries.size
  ensures res = -1 ∨ startIndex ≤ res ∧ res ≤ entryIndex ∧ Pure.isTurnStarter entries[res.toNat]!
  do
    let mut i : Int := entryIndex
    let mut _loopRet : Int := -1
    while i ≥ startIndex
      invariant i ≤ entryIndex
      invariant _loopRet = -1 ∨ startIndex ≤ _loopRet ∧ _loopRet ≤ entryIndex ∧ Pure.isTurnStarter entries[_loopRet.toNat]!
      done_with True
      decreasing (i - startIndex + 1).toNat
    do
      let _t0 ← isTurnStartEntry entries[i.toNat]!
      if _t0 then
        _loopRet := i
        break
      i := i - 1
    return _loopRet

method findCutPoint (entries : Array SessionEntry) (startIndex : Int) (endIndex : Int) (keepRecentTokens : Int) return (res : CutPointResult)
  require 0 ≤ startIndex
  require endIndex ≤ entries.size
  require ∀ j : Nat, startIndex < j → j < endIndex → Pure.isToolResultMessage entries[j]! → (match entries[j - 1]! with | .message .. => true | _ => false)
  ensures startIndex ≤ res.firstKeptEntryIndex ∧ res.firstKeptEntryIndex < endIndex ∧ ¬(Pure.isToolResultMessage entries[(res.firstKeptEntryIndex).toNat]!) ∨ res.firstKeptEntryIndex = startIndex
  ensures (∀ j : Nat, res.firstKeptEntryIndex ≤ j → j < endIndex → Pure.isToolResultMessage entries[j]! → 0 ≤ j - 1 ∧ res.firstKeptEntryIndex ≤ j - 1 ∧ (match entries[j - 1]! with | .message .. => true | _ => false)) ∨ res.firstKeptEntryIndex = startIndex
  ensures res.isSplitTurn → 0 ≤ res.turnStartIndex ∧ res.turnStartIndex < entries.size ∧ startIndex ≤ res.turnStartIndex ∧ res.turnStartIndex ≤ res.firstKeptEntryIndex ∧ Pure.isTurnStarter entries[(res.turnStartIndex).toNat]!
  do
    let _t1 ← findValidCutPoints entries startIndex endIndex
    let mut cutPoints : Array Int := _t1
    if cutPoints.size = 0 then
      return { firstKeptEntryIndex := startIndex, turnStartIndex := -1, isSplitTurn := false }
    let mut accumulatedTokens : Int := 0
    let mut cutIndex : Int := cutPoints[0]!
    let mut i : Int := endIndex - 1
    while i ≥ startIndex
      invariant i < endIndex
      invariant startIndex ≤ cutIndex
      invariant cutIndex < endIndex
      invariant ¬(Pure.isToolResultMessage entries[cutIndex.toNat]!)
      invariant ∀ k : Nat, k < cutPoints.size → startIndex ≤ cutPoints[k]! ∧ cutPoints[k]! < endIndex
      invariant ∀ k : Nat, k < cutPoints.size → ¬(Pure.isToolResultMessage entries[(cutPoints[k]!).toNat]!)
      done_with True
      decreasing (i - startIndex + 1).toNat
    do
      let entry := entries[i.toNat]!
      let messageTokens := ((sessionEntryToContextMessages entry).foldl (fun sum message => sum + estimateTokens message) 0)
      if messageTokens = 0 then
        i := i - 1
      else
        accumulatedTokens := accumulatedTokens + messageTokens
        if accumulatedTokens ≥ keepRecentTokens then
          let mut c : Nat := 0
          while c < cutPoints.size
            invariant startIndex ≤ cutIndex
            invariant cutIndex < endIndex
            invariant ¬(Pure.isToolResultMessage entries[cutIndex.toNat]!)
            invariant ∀ k : Nat, k < cutPoints.size → startIndex ≤ cutPoints[k]! ∧ cutPoints[k]! < endIndex
            invariant ∀ k : Nat, k < cutPoints.size → ¬(Pure.isToolResultMessage entries[(cutPoints[k]!).toNat]!)
            done_with True
            decreasing cutPoints.size - c
          do
            if cutPoints[c]! ≥ i then
              cutIndex := cutPoints[c]!
              break
            c := c + 1
          break
        i := i - 1
    while cutIndex > startIndex
      invariant startIndex ≤ cutIndex
      invariant cutIndex < endIndex
      invariant ¬(Pure.isToolResultMessage entries[cutIndex.toNat]!)
      done_with True
      decreasing (cutIndex - startIndex).toNat
    do
      let prevEntry := entries[(cutIndex - 1).toNat]!
      if (match prevEntry with | .compaction .. => true | _ => false) || (sessionEntryToContextMessages prevEntry).size > 0 then
        break
      cutIndex := cutIndex - 1
    let cutEntry := entries[cutIndex.toNat]!
    let _t2 ← isTurnStartEntry cutEntry
    let startsTurn := _t2
    let _t3 ← findTurnStartIndex entries cutIndex startIndex
    let turnStartIndex := if startsTurn then -1 else _t3
    return { firstKeptEntryIndex := cutIndex, turnStartIndex := turnStartIndex, isSplitTurn := !(startsTurn) && turnStartIndex ≠ -1 }
