// Generated by lsc from compaction.ts

datatype Option<T> = None | Some(value: T)

function {:axiom} estimateTokens(message: AgentMessage): int

function {:axiom} findTurnStartIndex(entries: seq<SessionEntry>, entryIndex: int, startIndex: int): int

datatype Role = bashExecution | custom | branchSummary | compactionSummary | user | assistant | toolResult

datatype AgentMessage = AgentMessage(role: Role)

datatype CutPointResult = CutPointResult(firstKeptEntryIndex: int, turnStartIndex: int, isSplitTurn: bool)

type Opaque_TextContent_or_ImageContent(==)

datatype ArrayOf_Opaque_TextContent_or_ImageContent_Or_string = ArrayBranch(arr: seq<Opaque_TextContent_or_ImageContent>) | NonArrayBranch(val: string)

datatype SessionEntry = message(message: AgentMessage, id: string, parentId: Option<string>, timestamp: string) | thinking_level_change(thinkingLevel: string, id: string, parentId: Option<string>, timestamp: string) | model_change(provider: string, modelId: string, id: string, parentId: Option<string>, timestamp: string) | compaction(summary: string, firstKeptEntryId: string, tokensBefore: int, details: Option<int>, fromHook: Option<bool>, id: string, parentId: Option<string>, timestamp: string) | branch_summary(fromId: string, summary: string, details: Option<int>, fromHook: Option<bool>, id: string, parentId: Option<string>, timestamp: string) | custom(customType: string, data: Option<int>, id: string, parentId: Option<string>, timestamp: string) | custom_message(customType: string, content: ArrayOf_Opaque_TextContent_or_ImageContent_Or_string, details: Option<int>, display: bool, id: string, parentId: Option<string>, timestamp: string) | label_(targetId: string, label_: Option<string>, id: string, parentId: Option<string>, timestamp: string) | session_info(name: Option<string>, id: string, parentId: Option<string>, timestamp: string)

datatype SessionMessageEntry = SessionMessageEntry(type_: string, message: AgentMessage, id: string, parentId: Option<string>, timestamp: string)

datatype ThinkingLevelChangeEntry = ThinkingLevelChangeEntry(type_: string, thinkingLevel: string, id: string, parentId: Option<string>, timestamp: string)

datatype ModelChangeEntry = ModelChangeEntry(type_: string, provider: string, modelId: string, id: string, parentId: Option<string>, timestamp: string)

datatype CompactionEntry = CompactionEntry(type_: string, summary: string, firstKeptEntryId: string, tokensBefore: int, details: Option<int>, fromHook: Option<bool>, id: string, parentId: Option<string>, timestamp: string)

datatype BranchSummaryEntry = BranchSummaryEntry(type_: string, fromId: string, summary: string, details: Option<int>, fromHook: Option<bool>, id: string, parentId: Option<string>, timestamp: string)

datatype CustomEntry = CustomEntry(type_: string, customType: string, data: Option<int>, id: string, parentId: Option<string>, timestamp: string)

datatype CustomMessageEntry = CustomMessageEntry(type_: string, customType: string, content: ArrayOf_Opaque_TextContent_or_ImageContent_Or_string, details: Option<int>, display: bool, id: string, parentId: Option<string>, timestamp: string)

datatype TextContent = TextContent(type_: string, text: string, textSignature: Option<string>)

datatype ImageContent = ImageContent(type_: string, data: string, mimeType: string)

datatype LabelEntry = LabelEntry(type_: string, targetId: string, label_: Option<string>, id: string, parentId: Option<string>, timestamp: string)

datatype SessionInfoEntry = SessionInfoEntry(type_: string, name: Option<string>, id: string, parentId: Option<string>, timestamp: string)

method findValidCutPoints(entries: seq<SessionEntry>, startIndex: int, endIndex: int) returns (res: seq<int>)
  requires (0 <= startIndex)
  requires (endIndex <= |entries|)
  ensures forall k: nat :: ((k < |res|) ==> ((startIndex <= res[k]) && (res[k] < endIndex)))
  ensures forall k: nat :: ((k < |res|) ==> !((entries[res[k]].message? && entries[res[k]].message.role.toolResult?)))
{
  var cutPoints: seq<int> := [];
  var i := startIndex;
  while (i < endIndex)
    invariant (startIndex <= i)
    invariant forall k: nat :: ((k < |cutPoints|) ==> ((startIndex <= cutPoints[k]) && (cutPoints[k] < endIndex)))
    invariant forall k: nat :: ((k < |cutPoints|) ==> !((entries[cutPoints[k]].message? && entries[cutPoints[k]].message.role.toolResult?)))
  {
    var entry := entries[i];
    match entry {
      case message(i_entry_message, i_entry_id, i_entry_parentId, i_entry_timestamp) =>
        var role := i_entry_message.role;
        match role {
          case bashExecution =>
            cutPoints := (cutPoints + [i]);
          case custom =>
            cutPoints := (cutPoints + [i]);
          case branchSummary =>
            cutPoints := (cutPoints + [i]);
          case compactionSummary =>
            cutPoints := (cutPoints + [i]);
          case user =>
            cutPoints := (cutPoints + [i]);
          case assistant =>
            cutPoints := (cutPoints + [i]);
          case toolResult =>

        }
      case thinking_level_change(i_entry_thinkingLevel, i_entry_id, i_entry_parentId, i_entry_timestamp) =>

      case model_change(i_entry_provider, i_entry_modelId, i_entry_id, i_entry_parentId, i_entry_timestamp) =>

      case compaction(i_entry_summary, i_entry_firstKeptEntryId, i_entry_tokensBefore, i_entry_details, i_entry_fromHook, i_entry_id, i_entry_parentId, i_entry_timestamp) =>

      case branch_summary(i_entry_fromId, i_entry_summary, i_entry_details, i_entry_fromHook, i_entry_id, i_entry_parentId, i_entry_timestamp) =>

      case custom(i_entry_customType, i_entry_data, i_entry_id, i_entry_parentId, i_entry_timestamp) =>

      case custom_message(i_entry_customType, i_entry_content, i_entry_details, i_entry_display, i_entry_id, i_entry_parentId, i_entry_timestamp) =>

      case label_(i_entry_targetId, i_entry_label, i_entry_id, i_entry_parentId, i_entry_timestamp) =>

      case session_info(i_entry_name, i_entry_id, i_entry_parentId, i_entry_timestamp) =>

    }
    if (entry.branch_summary? || entry.custom_message?) {
      cutPoints := (cutPoints + [i]);
    }
    i := (i + 1);
  }
  return cutPoints;
}

method findCutPoint(entries: seq<SessionEntry>, startIndex: int, endIndex: int, keepRecentTokens: int) returns (res: CutPointResult)
  requires (0 <= startIndex)
  requires (endIndex <= |entries|)
  requires forall j: nat :: ((startIndex < j) ==> (j < endIndex) ==> entries[j].message? ==> entries[j].message.role.toolResult? ==> entries[(j - 1)].message?)
  ensures ((((startIndex <= res.firstKeptEntryIndex) && (res.firstKeptEntryIndex < endIndex)) && !((entries[res.firstKeptEntryIndex].message? && entries[res.firstKeptEntryIndex].message.role.toolResult?))) || (res.firstKeptEntryIndex == startIndex))
  ensures ((forall j: nat :: ((res.firstKeptEntryIndex <= j) ==> (j < endIndex) ==> entries[j].message? ==> entries[j].message.role.toolResult? ==> (((0 <= (j - 1)) && (res.firstKeptEntryIndex <= (j - 1))) && entries[(j - 1)].message?))) || (res.firstKeptEntryIndex == startIndex))
{
  var i_t0 := findValidCutPoints(entries, startIndex, endIndex);
  var cutPoints := i_t0;
  if (|cutPoints| == 0) {
    return CutPointResult(startIndex, -1, false);
  }
  var accumulatedTokens := 0;
  var cutIndex := cutPoints[0];
  var i := (endIndex - 1);
  while (i >= startIndex)
    invariant (i < endIndex)
    invariant (startIndex <= cutIndex)
    invariant (cutIndex < endIndex)
    invariant !((entries[cutIndex].message? && entries[cutIndex].message.role.toolResult?))
  {
    var entry := entries[i];
    match entry {
      case message(i_entry_message, i_entry_id, i_entry_parentId, i_entry_timestamp) =>
        var messageTokens := estimateTokens(i_entry_message);
        accumulatedTokens := (accumulatedTokens + messageTokens);
        if (accumulatedTokens >= keepRecentTokens) {
          var c := 0;
          while (c < |cutPoints|)
            invariant (startIndex <= cutIndex)
            invariant (cutIndex < endIndex)
            invariant !((entries[cutIndex].message? && entries[cutIndex].message.role.toolResult?))
          {
            if (cutPoints[c] >= i) {
              cutIndex := cutPoints[c];
              break;
            }
            c := (c + 1);
          }
          break;
        }
        i := (i - 1);
      case _ =>
        i := (i - 1);
    }
  }
  while (cutIndex > startIndex)
    invariant (startIndex <= cutIndex)
    invariant (cutIndex < endIndex)
    invariant !((entries[cutIndex].message? && entries[cutIndex].message.role.toolResult?))
  {
    var prevEntry := entries[(cutIndex - 1)];
    match prevEntry {
      case compaction(i_prevEntry_summary, i_prevEntry_firstKeptEntryId, i_prevEntry_tokensBefore, i_prevEntry_details, i_prevEntry_fromHook, i_prevEntry_id, i_prevEntry_parentId, i_prevEntry_timestamp) =>
        break;
      case message(i_prevEntry_message, i_prevEntry_id, i_prevEntry_parentId, i_prevEntry_timestamp) =>
        break;
      case _ =>
        cutIndex := (cutIndex - 1);
    }
  }
  var cutEntry := entries[cutIndex];
  var isUserMessage := (cutEntry.message? && cutEntry.message.role.user?);
  var turnStartIndex := (if isUserMessage then -1 else findTurnStartIndex(entries, cutIndex, startIndex));
  return CutPointResult(cutIndex, turnStartIndex, (!(isUserMessage) && (turnStartIndex != -1)));
}
