/-
  Generated by lsc from compaction.ts
  Do not edit — re-run `lsc gen` to regenerate.
-/
import «compaction.types»

set_option loom.semantics.termination "total"
set_option loom.semantics.choice "demonic"

method isToolResultMessage (entry : SessionEntry) return (res : Bool)
  do
    return Pure.isToolResultMessage entry

method isTurnStarter (entry : SessionEntry) return (res : Bool)
  do
    return Pure.isTurnStarter entry

method findValidCutPoints (entries : Array SessionEntry) (startIndex : Int) (endIndex : Int) return (res : Array Int)
  require 0 ≤ startIndex
  require endIndex ≤ entries.size
  ensures ∀ k : Nat, k < res.size → startIndex ≤ res[k]! ∧ res[k]! < endIndex
  ensures ∀ k : Nat, k < res.size → ¬(Pure.isToolResultMessage entries[(res[k]!).toNat]!)
  do
    let mut cutPoints : Array Int := #[]
    let mut i : Int := startIndex
    while i < endIndex
      invariant startIndex ≤ i
      invariant ∀ k : Nat, k < cutPoints.size → startIndex ≤ cutPoints[k]! ∧ cutPoints[k]! < endIndex
      invariant ∀ k : Nat, k < cutPoints.size → ¬(Pure.isToolResultMessage entries[(cutPoints[k]!).toNat]!)
    do
      let entry := entries[i.toNat]!
      if (match entry with | .message .. => true | _ => false) then
        let _entry_message := (match entry with | .message _v _ _ _ => _v | _ => (default : AgentMessage))
        let role := _entry_message.role
        if role = Role.bashExecution then
          cutPoints := Array.push cutPoints i
        else if role = Role.custom then
          cutPoints := Array.push cutPoints i
        else
          if role = Role.branchSummary then
            cutPoints := Array.push cutPoints i
          else if role = Role.compactionSummary then
            cutPoints := Array.push cutPoints i
          else
            if role = Role.user then
              cutPoints := Array.push cutPoints i
            else if role = Role.assistant then
              cutPoints := Array.push cutPoints i
      if (match entry with | .branch_summary .. => true | _ => false) || (match entry with | .custom_message .. => true | _ => false) then
        cutPoints := Array.push cutPoints i
      i := i + 1
    return cutPoints

method findTurnStartIndex (entries : Array SessionEntry) (entryIndex : Int) (startIndex : Int) return (res : Int)
  require 0 ≤ startIndex
  require entryIndex < entries.size
  ensures res = -1 ∨ startIndex ≤ res ∧ res ≤ entryIndex ∧ Pure.isTurnStarter entries[res.toNat]!
  do
    let mut i : Int := entryIndex
    let mut _loopRet : Int := -1
    while i ≥ startIndex
      invariant i ≤ entryIndex
      invariant _loopRet = -1 ∨ startIndex ≤ _loopRet ∧ _loopRet ≤ entryIndex ∧ Pure.isTurnStarter entries[_loopRet.toNat]!
      done_with True
    do
      let entry := entries[i.toNat]!
      if (match entry with | .branch_summary .. => true | _ => false) || (match entry with | .custom_message .. => true | _ => false) then
        _loopRet := i
        break
      if (match entry with | .message .. => true | _ => false) then
        let _entry_message := (match entry with | .message _v _ _ _ => _v | _ => (default : AgentMessage))
        let role := _entry_message.role
        if role = Role.user || role = Role.bashExecution then
          _loopRet := i
          break
      i := i - 1
    return _loopRet

method findCutPoint (entries : Array SessionEntry) (startIndex : Int) (endIndex : Int) (keepRecentTokens : Int) return (res : CutPointResult)
  require 0 ≤ startIndex
  require endIndex ≤ entries.size
  require ∀ j : Nat, startIndex < j → j < endIndex → Pure.isToolResultMessage entries[j]! → (match entries[j - 1]! with | .message .. => true | _ => false)
  ensures startIndex ≤ res.firstKeptEntryIndex ∧ res.firstKeptEntryIndex < endIndex ∧ ¬(Pure.isToolResultMessage entries[(res.firstKeptEntryIndex).toNat]!) ∨ res.firstKeptEntryIndex = startIndex
  ensures (∀ j : Nat, res.firstKeptEntryIndex ≤ j → j < endIndex → Pure.isToolResultMessage entries[j]! → 0 ≤ j - 1 ∧ res.firstKeptEntryIndex ≤ j - 1 ∧ (match entries[j - 1]! with | .message .. => true | _ => false)) ∨ res.firstKeptEntryIndex = startIndex
  ensures res.isSplitTurn → 0 ≤ res.turnStartIndex ∧ res.turnStartIndex < entries.size ∧ startIndex ≤ res.turnStartIndex ∧ res.turnStartIndex ≤ res.firstKeptEntryIndex ∧ Pure.isTurnStarter entries[(res.turnStartIndex).toNat]!
  do
    let _t0 ← findValidCutPoints entries startIndex endIndex
    let mut cutPoints : Array Int := _t0
    if cutPoints.size = 0 then
      return { firstKeptEntryIndex := startIndex, turnStartIndex := -1, isSplitTurn := false }
    let mut accumulatedTokens : Int := 0
    let mut cutIndex : Int := cutPoints[0]!
    let mut i : Int := endIndex - 1
    while i ≥ startIndex
      invariant i < endIndex
      invariant startIndex ≤ cutIndex
      invariant cutIndex < endIndex
      invariant ¬(Pure.isToolResultMessage entries[cutIndex.toNat]!)
      done_with True
    do
      let entry := entries[i.toNat]!
      if (match entry with | .message .. => true | _ => false) then
        let _entry_message := (match entry with | .message _v _ _ _ => _v | _ => (default : AgentMessage))
        let messageTokens := estimateTokens _entry_message
        accumulatedTokens := accumulatedTokens + messageTokens
        if accumulatedTokens ≥ keepRecentTokens then
          let mut c : Int := 0
          while c < cutPoints.size
            invariant startIndex ≤ cutIndex
            invariant cutIndex < endIndex
            invariant ¬(Pure.isToolResultMessage entries[cutIndex.toNat]!)
            done_with True
          do
            if cutPoints[c.toNat]! ≥ i then
              cutIndex := cutPoints[c.toNat]!
              break
            c := c + 1
          break
        i := i - 1
      else
        i := i - 1
    while cutIndex > startIndex
      invariant startIndex ≤ cutIndex
      invariant cutIndex < endIndex
      invariant ¬(Pure.isToolResultMessage entries[cutIndex.toNat]!)
      done_with True
    do
      let prevEntry := entries[(cutIndex - 1).toNat]!
      if (match prevEntry with | .compaction .. => true | _ => false) then
        break
      else if (match prevEntry with | .message .. => true | _ => false) then
        break
      else
        cutIndex := cutIndex - 1
    let cutEntry := entries[cutIndex.toNat]!
    let isUserMessage := (match cutEntry with | .message .. => true | _ => false) && ((match cutEntry with | .message _v _ _ _ => _v | _ => (default : AgentMessage))).role = Role.user
    let _t1 ← findTurnStartIndex entries cutIndex startIndex
    let turnStartIndex := if isUserMessage then -1 else _t1
    return { firstKeptEntryIndex := cutIndex, turnStartIndex := turnStartIndex, isSplitTurn := !(isUserMessage) && turnStartIndex ≠ -1 }
