// Generated by lsc from compaction.ts

datatype Option<T> = None | Some(value: T)

type Unknown(==, 0)

function {:axiom} createCustomMessage(customType: string, content: Unknown, display: bool, details: Unknown, timestamp: string): AgentMessage

function {:axiom} createBranchSummaryMessage(summary: string, fromId: string, timestamp: string): AgentMessage

function {:axiom} createCompactionSummaryMessage(summary: string, tokensBefore: int, timestamp: string): AgentMessage

function {:axiom} estimateTokens(message: AgentMessage): int

function {:axiom} sessionEntryToContextMessages(entry: SessionEntry): seq<AgentMessage>
  ensures (entry.message? ==> (|sessionEntryToContextMessages(entry)| >= 1))
  ensures forall k: nat :: ((k < |sessionEntryToContextMessages(entry)|) ==> ((!entry.message?) || (sessionEntryToContextMessages(entry)[k].role == entry.message.role)))
  ensures forall k: nat :: ((k < |sessionEntryToContextMessages(entry)|) ==> ((!entry.custom_message?) || sessionEntryToContextMessages(entry)[k].role.custom?))
  ensures forall k: nat :: ((k < |sessionEntryToContextMessages(entry)|) ==> ((!entry.branch_summary?) || sessionEntryToContextMessages(entry)[k].role.branchSummary?))
  ensures ((((entry.message? || entry.custom_message?) || entry.branch_summary?) || entry.compaction?) || (|sessionEntryToContextMessages(entry)| == 0))

datatype Role = bashExecution | custom | branchSummary | compactionSummary | user | assistant | toolResult

datatype AgentMessage = AgentMessage(role: Role)

datatype CutPointResult = CutPointResult(firstKeptEntryIndex: int, turnStartIndex: int, isSplitTurn: bool)

type Opaque_TextContent_or_ImageContent(==)

datatype ArrayOf_Opaque_TextContent_or_ImageContent_Or_string = ArrayBranch(arr: seq<Opaque_TextContent_or_ImageContent>) | NonArrayBranch(val: string)

datatype SessionEntry = message(message: AgentMessage, id: string, parentId: Option<string>, timestamp: string) | thinking_level_change(thinkingLevel: string, id: string, parentId: Option<string>, timestamp: string) | model_change(provider: string, modelId: string, id: string, parentId: Option<string>, timestamp: string) | compaction(summary: string, firstKeptEntryId: string, tokensBefore: int, details: Option<Unknown>, fromHook: Option<bool>, id: string, parentId: Option<string>, timestamp: string) | branch_summary(fromId: string, summary: string, details: Option<Unknown>, fromHook: Option<bool>, id: string, parentId: Option<string>, timestamp: string) | custom(customType: string, data: Option<Unknown>, id: string, parentId: Option<string>, timestamp: string) | custom_message(customType: string, content: ArrayOf_Opaque_TextContent_or_ImageContent_Or_string, details: Option<Unknown>, display: bool, id: string, parentId: Option<string>, timestamp: string) | label_(targetId: string, label_: Option<string>, id: string, parentId: Option<string>, timestamp: string) | session_info(name: Option<string>, id: string, parentId: Option<string>, timestamp: string)

datatype SessionMessageEntry = SessionMessageEntry(type_: string, message: AgentMessage, id: string, parentId: Option<string>, timestamp: string)

datatype ThinkingLevelChangeEntry = ThinkingLevelChangeEntry(type_: string, thinkingLevel: string, id: string, parentId: Option<string>, timestamp: string)

datatype ModelChangeEntry = ModelChangeEntry(type_: string, provider: string, modelId: string, id: string, parentId: Option<string>, timestamp: string)

datatype CompactionEntry = CompactionEntry(type_: string, summary: string, firstKeptEntryId: string, tokensBefore: int, details: Option<Unknown>, fromHook: Option<bool>, id: string, parentId: Option<string>, timestamp: string)

datatype BranchSummaryEntry = BranchSummaryEntry(type_: string, fromId: string, summary: string, details: Option<Unknown>, fromHook: Option<bool>, id: string, parentId: Option<string>, timestamp: string)

datatype CustomEntry = CustomEntry(type_: string, customType: string, data: Option<Unknown>, id: string, parentId: Option<string>, timestamp: string)

datatype CustomMessageEntry = CustomMessageEntry(type_: string, customType: string, content: ArrayOf_Opaque_TextContent_or_ImageContent_Or_string, details: Option<Unknown>, display: bool, id: string, parentId: Option<string>, timestamp: string)

datatype TextContent = TextContent(type_: string, text: string, textSignature: Option<string>)

datatype ImageContent = ImageContent(type_: string, data: string, mimeType: string)

datatype LabelEntry = LabelEntry(type_: string, targetId: string, label_: Option<string>, id: string, parentId: Option<string>, timestamp: string)

datatype SessionInfoEntry = SessionInfoEntry(type_: string, name: Option<string>, id: string, parentId: Option<string>, timestamp: string)

function isToolResultMessage(entry: SessionEntry): bool
{
  (entry.message? && entry.message.role.toolResult?)
}

function isTurnStarter(entry: SessionEntry): bool
{
  ((entry.branch_summary? || entry.custom_message?) || (entry.message? && isTurnStartMessage(entry.message)))
}

function isCutPointMessage(message: AgentMessage): bool
{
  match message.role {
    case user =>
      true
    case assistant =>
      true
    case bashExecution =>
      true
    case custom =>
      true
    case branchSummary =>
      true
    case compactionSummary =>
      true
    case toolResult =>
      false
  }
}

function isTurnStartMessage(message: AgentMessage): bool
{
  match message.role {
    case user =>
      true
    case bashExecution =>
      true
    case custom =>
      true
    case branchSummary =>
      true
    case compactionSummary =>
      true
    case assistant =>
      false
    case toolResult =>
      false
  }
}

function isTurnStartEntry(entry: SessionEntry): bool
{
  match entry {
    case compaction(i_entry_summary, i_entry_firstKeptEntryId, i_entry_tokensBefore, i_entry_details, i_entry_fromHook, i_entry_id, i_entry_parentId, i_entry_timestamp) =>
      false
    case _ =>
      (exists x :: x in sessionEntryToContextMessages(entry) && isTurnStartMessage(x))
  }
}

lemma isTurnStartEntry_ensures(entry: SessionEntry)
  ensures ((isTurnStartEntry(entry) == false) || isTurnStarter(entry))
{
}

method findValidCutPoints(entries: seq<SessionEntry>, startIndex: int, endIndex: int) returns (res: seq<int>)
  requires (0 <= startIndex)
  requires (endIndex <= |entries|)
  ensures forall k: nat :: ((k < |res|) ==> ((startIndex <= res[k]) && (res[k] < endIndex)))
  ensures forall k: nat :: ((k < |res|) ==> !(isToolResultMessage(entries[res[k]])))
{
  var cutPoints: seq<int> := [];
  var i := startIndex;
  while (i < endIndex)
    invariant (startIndex <= i)
    invariant forall k: nat :: ((k < |cutPoints|) ==> ((startIndex <= cutPoints[k]) && (cutPoints[k] < endIndex)))
    invariant forall k: nat :: ((k < |cutPoints|) ==> !(isToolResultMessage(entries[cutPoints[k]])))
    decreases (endIndex - i)
  {
    var entry := entries[i];
    match entry {
      case compaction(i_entry_summary, i_entry_firstKeptEntryId, i_entry_tokensBefore, i_entry_details, i_entry_fromHook, i_entry_id, i_entry_parentId, i_entry_timestamp) =>
        i := (i + 1);
      case _ =>
        if (exists x :: x in sessionEntryToContextMessages(entry) && isCutPointMessage(x)) {
          cutPoints := (cutPoints + [i]);
        }
        i := (i + 1);
    }
  }
  return cutPoints;
}

method findTurnStartIndex(entries: seq<SessionEntry>, entryIndex: int, startIndex: int) returns (res: int)
  requires (0 <= startIndex)
  requires (entryIndex < |entries|)
  ensures ((res == -1) || (((startIndex <= res) && (res <= entryIndex)) && isTurnStarter(entries[res])))
{
  var i := entryIndex;
  while (i >= startIndex)
    invariant (i <= entryIndex)
    decreases ((i - startIndex) + 1)
  {
    var i_t0 := isTurnStartEntry(entries[i]);
    if i_t0 {
      return i;
    }
    i := (i - 1);
  }
  return -1;
}

method findCutPoint(entries: seq<SessionEntry>, startIndex: int, endIndex: int, keepRecentTokens: int) returns (res: CutPointResult)
  requires (0 <= startIndex)
  requires (endIndex <= |entries|)
  requires forall j: nat :: ((startIndex < j) ==> (j < endIndex) ==> isToolResultMessage(entries[j]) ==> entries[(j - 1)].message?)
  ensures ((((startIndex <= res.firstKeptEntryIndex) && (res.firstKeptEntryIndex < endIndex)) && !(isToolResultMessage(entries[res.firstKeptEntryIndex]))) || (res.firstKeptEntryIndex == startIndex))
  ensures ((forall j: nat :: ((res.firstKeptEntryIndex <= j) ==> (j < endIndex) ==> isToolResultMessage(entries[j]) ==> (((0 <= (j - 1)) && (res.firstKeptEntryIndex <= (j - 1))) && entries[(j - 1)].message?))) || (res.firstKeptEntryIndex == startIndex))
  ensures (res.isSplitTurn ==> (((((0 <= res.turnStartIndex) && (res.turnStartIndex < |entries|)) && (startIndex <= res.turnStartIndex)) && (res.turnStartIndex <= res.firstKeptEntryIndex)) && isTurnStarter(entries[res.turnStartIndex])))
{
  var i_t1 := findValidCutPoints(entries, startIndex, endIndex);
  var cutPoints := i_t1;
  if (|cutPoints| == 0) {
    return CutPointResult(startIndex, -1, false);
  }
  var accumulatedTokens := 0;
  var cutIndex := cutPoints[0];
  var i := (endIndex - 1);
  while (i >= startIndex)
    invariant (i < endIndex)
    invariant (startIndex <= cutIndex)
    invariant (cutIndex < endIndex)
    invariant !(isToolResultMessage(entries[cutIndex]))
    invariant forall k: nat :: ((k < |cutPoints|) ==> ((startIndex <= cutPoints[k]) && (cutPoints[k] < endIndex)))
    invariant forall k: nat :: ((k < |cutPoints|) ==> !(isToolResultMessage(entries[cutPoints[k]])))
    decreases ((i - startIndex) + 1)
  {
    var entry := entries[i];
    var messageTokens := Std.Collections.Seq.FoldLeft((sum: int, message: AgentMessage) => (sum + estimateTokens(message)), 0, sessionEntryToContextMessages(entry));
    if (messageTokens == 0) {
      i := (i - 1);
    } else {
      accumulatedTokens := (accumulatedTokens + messageTokens);
      if (accumulatedTokens >= keepRecentTokens) {
        var c := 0;
        while (c < |cutPoints|)
          invariant (startIndex <= cutIndex)
          invariant (cutIndex < endIndex)
          invariant !(isToolResultMessage(entries[cutIndex]))
          invariant forall k: nat :: ((k < |cutPoints|) ==> ((startIndex <= cutPoints[k]) && (cutPoints[k] < endIndex)))
          invariant forall k: nat :: ((k < |cutPoints|) ==> !(isToolResultMessage(entries[cutPoints[k]])))
          decreases (|cutPoints| - c)
        {
          if (cutPoints[c] >= i) {
            cutIndex := cutPoints[c];
            break;
          }
          c := (c + 1);
        }
        break;
      }
      i := (i - 1);
    }
  }
  while (cutIndex > startIndex)
    invariant (startIndex <= cutIndex)
    invariant (cutIndex < endIndex)
    invariant !(isToolResultMessage(entries[cutIndex]))
    decreases (cutIndex - startIndex)
  {
    var prevEntry := entries[(cutIndex - 1)];
    if (prevEntry.compaction? || (|sessionEntryToContextMessages(prevEntry)| > 0)) {
      break;
    }
    cutIndex := (cutIndex - 1);
  }
  var cutEntry := entries[cutIndex];
  var i_t2 := isTurnStartEntry(cutEntry);
  var startsTurn := i_t2;
  var i_t3 := findTurnStartIndex(entries, cutIndex, startIndex);
  var turnStartIndex := (if startsTurn then -1 else i_t3);
  return CutPointResult(cutIndex, turnStartIndex, (!(startsTurn) && (turnStartIndex != -1)));
}
