/-
  Generated by lsc — Lean types and pure function mirrors.
-/
import LemmaScript

/-- Opaque carrier for `unknown`-typed values (mirrors Dafny's `type Unknown(==, 0)`). -/
opaque Unknown : Type

inductive Role where
  | bashExecution : Role
  | custom : Role
  | branchSummary : Role
  | compactionSummary : Role
  | user : Role
  | assistant : Role
  | toolResult : Role
deriving Repr, Inhabited, DecidableEq

structure AgentMessage where
  role : Role
deriving Repr, Inhabited, DecidableEq

structure CutPointResult where
  firstKeptEntryIndex : Int
  turnStartIndex : Int
  isSplitTurn : Bool
deriving Repr, Inhabited, DecidableEq

opaque Opaque_TextContent_or_ImageContent : Type

inductive ArrayOf_Opaque_TextContent_or_ImageContent_Or_string where
  | ArrayBranch (arr : Array Opaque_TextContent_or_ImageContent) : ArrayOf_Opaque_TextContent_or_ImageContent_Or_string
  | NonArrayBranch (val : String) : ArrayOf_Opaque_TextContent_or_ImageContent_Or_string
deriving Inhabited

inductive SessionEntry where
  | message (message : AgentMessage) (id : String) (parentId : Option String) (timestamp : String) : SessionEntry
  | thinking_level_change (thinkingLevel : String) (id : String) (parentId : Option String) (timestamp : String) : SessionEntry
  | model_change (provider : String) (modelId : String) (id : String) (parentId : Option String) (timestamp : String) : SessionEntry
  | compaction (summary : String) (firstKeptEntryId : String) (tokensBefore : Int) (details : Option Unknown) (fromHook : Option Bool) (id : String) (parentId : Option String) (timestamp : String) : SessionEntry
  | branch_summary (fromId : String) (summary : String) (details : Option Unknown) (fromHook : Option Bool) (id : String) (parentId : Option String) (timestamp : String) : SessionEntry
  | custom (customType : String) (data : Option Unknown) (id : String) (parentId : Option String) (timestamp : String) : SessionEntry
  | custom_message (customType : String) (content : ArrayOf_Opaque_TextContent_or_ImageContent_Or_string) (details : Option Unknown) (display : Bool) (id : String) (parentId : Option String) (timestamp : String) : SessionEntry
  | label (targetId : String) (label : Option String) (id : String) (parentId : Option String) (timestamp : String) : SessionEntry
  | session_info (name : Option String) (id : String) (parentId : Option String) (timestamp : String) : SessionEntry
deriving Inhabited

structure SessionMessageEntry where
  type : String
  message : AgentMessage
  id : String
  parentId : Option String
  timestamp : String
deriving Repr, Inhabited, DecidableEq

structure ThinkingLevelChangeEntry where
  type : String
  thinkingLevel : String
  id : String
  parentId : Option String
  timestamp : String
deriving Repr, Inhabited, DecidableEq

structure ModelChangeEntry where
  type : String
  provider : String
  modelId : String
  id : String
  parentId : Option String
  timestamp : String
deriving Repr, Inhabited, DecidableEq

structure CompactionEntry where
  type : String
  summary : String
  firstKeptEntryId : String
  tokensBefore : Int
  details : Option Unknown
  fromHook : Option Bool
  id : String
  parentId : Option String
  timestamp : String
deriving Inhabited

structure BranchSummaryEntry where
  type : String
  fromId : String
  summary : String
  details : Option Unknown
  fromHook : Option Bool
  id : String
  parentId : Option String
  timestamp : String
deriving Inhabited

structure CustomEntry where
  type : String
  customType : String
  data : Option Unknown
  id : String
  parentId : Option String
  timestamp : String
deriving Inhabited

structure CustomMessageEntry where
  type : String
  customType : String
  content : ArrayOf_Opaque_TextContent_or_ImageContent_Or_string
  details : Option Unknown
  display : Bool
  id : String
  parentId : Option String
  timestamp : String
deriving Inhabited

structure TextContent where
  type : String
  text : String
  textSignature : Option String
deriving Repr, Inhabited, DecidableEq

structure ImageContent where
  type : String
  data : String
  mimeType : String
deriving Repr, Inhabited, DecidableEq

structure LabelEntry where
  type : String
  targetId : String
  label : Option String
  id : String
  parentId : Option String
  timestamp : String
deriving Repr, Inhabited, DecidableEq

structure SessionInfoEntry where
  type : String
  name : Option String
  id : String
  parentId : Option String
  timestamp : String
deriving Repr, Inhabited, DecidableEq

opaque estimateTokens (message : AgentMessage) : Int

namespace Pure

def isToolResultMessage (entry : SessionEntry) : Bool :=
  (match entry with | .message .. => true | _ => false) && ((match entry with | .message _v _ _ _ => _v | _ => (default : AgentMessage))).role = Role.toolResult

def isTurnStarter (entry : SessionEntry) : Bool :=
  (match entry with | .branch_summary .. => true | _ => false) || (match entry with | .custom_message .. => true | _ => false) || (match entry with | .message .. => true | _ => false) && (((match entry with | .message _v _ _ _ => _v | _ => (default : AgentMessage))).role = Role.user || ((match entry with | .message _v _ _ _ => _v | _ => (default : AgentMessage))).role = Role.bashExecution)

end Pure
